//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class производитель
    {
        public int ID_Prod { get; set; }
        public string Name_Prod { get; set; }
        public System.DateTime Data_creature { get; set; }
        public string Type { get; set; }
    }
}
